### ISSUE TITLE
`emnapi` breaking changes related to my criminal affair

### ISSUE THREAD

**Issue by mmomtchev** [mmomtchev/swig#20]
Google, which are heavily involved in my affair just intervened to introduce a breaking change in `emnapi` after the release of SWIG JSE

**Comment by mmomtchev** [comment]
*A number of people posted various simultaneous comments in order to show that it was on a purpose*

**Comment by toyobayashi** [comment]
Just noticed this issue title when I searched issues about emnapi on GitHub, to clarify, currently I'm the only maintainer of emnapi, and I'm just a person who needs an English translator to communicate on GitHub. Those breaking changes was introduced by me, I have nothing to do with Google and also have nothing to do with your situation. Thank you for your understanding and all contributions to emnapi. If you still feel uncomfortable, you can stop using emnapi or fork it yourself for your own maintenance.

**Comment by mmomtchev** [comment]
However each time you post anything, I also receive simultaneous messages from other participants in that affair - this time it was my insurance company who used a falsified statement against a few months ago. So please, forget about any excuses.

**Comment by toyobayashi** [comment]
There is no excuse because your comments seem to be defaming me and now I am the one who is troubled. If you don't believe me, there's nothing I can do about it. I recommend you maintain emnapi yourself. I want nothing to do with your situation please. Thanks.

**Comment by mmomtchev** [comment]
Ok, then please go away.
