### ISSUE TITLE
Incorrect handling of `std::shared_ptr<>` arguments

### ISSUE THREAD

**Issue by mateusz-plociennik** [mmomtchev/swig#71]
I have the following interface (note: I am trying to provide a minimal working example) that I am wrapping with SWIG:
```cpp
class RpcDevice
{
public:
	using SharedPtr = std::shared_ptr<RpcDevice>;
	virtual ~RpcDevice() = default;

protected:
	RpcDevice() = default;
};

RpcDevice::SharedPtr getTcpDevice(const std::string& ipAddress);

class DisplayServer
{
public:
	DisplayServer();
	~DisplayServer();

	void init(RpcDevice::SharedPtr device, unsigned int timeoutMs = 0);
};
```
and:
```swig
%module rpc

%include <std_shared_ptr.i>
%shared_ptr(RpcDevice)
```

The generated code for argument 2 of `DisplayServer::init()` looks like below:
```cpp
{
  RpcDevice *plain_ptr;
  int res = SWIG_ConvertPtr(info[0], reinterpret_cast<void**>(&plain_ptr), SWIGTYPE_p_BlamOSRPC__RpcDevice,  0 );
  if (!SWIG_IsOK(res)) {
    SWIG_exception_fail(SWIG_ArgError(res), "in method '" "DisplayServer_init" "', argument " "2"" of type '" "RpcDevice""'");
  }
  arg2 = std::shared_ptr< RpcDevice>(plain_ptr, SWIG_null_deleter());
}
```

It looks like the wrapper strips out the raw pointer and encapsulates it again into the new `std::shared_ptr`, which is pretty questionable behaviour.

**Comment by mateusz-plociennik** [comment]
I have a case where garbage collector destructs the original object `getTcpDevice()` and then on `DisplayServer` destruction I am getting a crash, because the `RpcDevice` is no longer there.

**Comment by mmomtchev** [comment]
This has nothing to do with `std::shared_ptr`, it is a persistence problem. Normally the arguments should be protected from the GC during the duration of the execution of the called function. I suppose this only happens in async mode? Do you have locking enabled? Can you post the generated function?

**Comment by mmomtchev** [comment]
Or maybe you have two distinct functions, one which returns a `shared_ptr` and another which takes a `shared_ptr` and keeps it for future use across different calls?

In this case, you may be better off without the `shared_ptr` support in SWIG at all - simply wrap the `shared_ptr` and use it as an opaque type.

**Comment by mateusz-plociennik** [comment]
Yes, it is definitely a persistence problem. And yes, it is async code. I am working on a custom Appium driver (similar to [this one](https://github.com/appium/appium/blob/master/packages/fake-driver/lib/driver.js)), so there’s a driver class that holds the RpcDevice and DisplayServer instances.

[Locking](https://html-preview.github.io/?url=https://github.com/mmomtchev/swig/blob/main/Doc/Manual/Javascript.html#Javascript_async_locking) is probably disabled (I haven’t touched the async:locking flag). I don't fully understand the prerequisites here.

I would like to use some member functions of RpcDevice, so the opaque type doesn’t quite work for me.

**Comment by mateusz-plociennik** [comment]
What would be the best approach if I need to explicitly destroy `RpcDevice` and all service objects (like `DisplayServer`) at the end of the driver session? I can’t wait for the garbage collector to kick in. How can I destroy the object in question immediately?

**Comment by mmomtchev** [comment]
You can't destroy a JavaScript object, this is a limitation in how the GC works. You can eventually use `%extend` to add a method that *closes* an object - the JavaScript object will remain for some time afterwards, but the underlying resources will be released.

**Comment by mateusz-plociennik** [comment]
Yes, sorted that out with the following wrappers. Thank you for your help. Take care!
```swig
%define WRAP_SHARED_PTR(CLASS_NAME, SHORT_NAME)
%extend std::shared_ptr<CLASS_NAME> {
    void destroy() { $self->reset(); }
	CLASS_NAME* operator->() { return $self->get(); }
}
%template(SHORT_NAME) std::shared_ptr<CLASS_NAME>;
%enddef

WRAP_SHARED_PTR(RpcDevice, RpcDevicePtr);

%define WRAP_UNIQUE_PTR(CLASS_NAME, SHORT_NAME)
%extend std::unique_ptr<CLASS_NAME> {
	unique_ptr() { return new std::unique_ptr(std::make_unique<CLASS_NAME>()); }
    void destroy() { $self->reset(); }
	CLASS_NAME* operator->() { return $self->get(); }
}
%ignore std::unique_ptr<CLASS_NAME>::unique_ptr;
%template(SHORT_NAME) std::unique_ptr<CLASS_NAME>;
%enddef

WRAP_UNIQUE_PTR(DisplayServer, DisplayServerPtr);
```
